### PR TITLE
Get Kubernetes Version: Adds Retry Logic 

### LINKED ISSUE #551: Integration tests: why do pods fail sometimes?
Running the integrations tests I see output like this: 

```
using ticker and an timer...
thePod (kube-bench-t55bx) - status:"Running" 
using ticker and an timer...
thePod (kube-bench-t55bx) - status:"Running" 
using ticker and an timer...
thePod (kube-bench-t55bx) - status:"Failed" 
thePod (kube-bench-t55bx) - Failed - retrying...
Found (2) pods
pod (kube-bench-wfr6z) - "Pending"
using ticker and an timer...
thePod (kube-bench-wfr6z) - status:"Succeeded" 
=== RUN   TestRunWithKind/job-node
```
I think these pods are running the kube-bench job, but why does the first of them fail? And why doesn't this matter for the integration test to succeed?

### PR DESCRIPTION
**Pull request by robertojrojas**
When getting the Kubernetes version this code uses a retry logic in case errors like DNS not ready happen.
 
Closes #551

### CODE REVIEW

File: cmd/kubernetes_version.go [hunk 1]
```diff
@@ -42,6 +43,20 @@ func getKubeVersionFromRESTAPI() (string, error) {
 	return k8sVersion, nil
 }
 
+func getWebDataWithRetry(k8sVersionURL, token string, cacert *tls.Certificate) (data []byte, err error) {
+	tries := 0
+	for tries < 10 {
```
Comment (lizrice) [inline cmd/kubernetes_version.go]:
```suggestion
      // We retry a few times in case the DNS service has not had time to come up
	for tries < 10 {
```

Suggest adding a comment so that we know why it's an arbitrary number of retries, and in case we ever need to increase that number
