### PR TITLE
bugfix: false negative when audit_config is defined along with audit …

### LINKED ISSUE #1242: cfg/cis-1.6's 4.2.1 get a false negative result
**Overview**
if kubelet run only with cmd parameter `--anonymous-auth=false` and cannot find configuration file in server, cis-1.6-4.2.1 rule will get a false negative result

**How did you run kube-bench?**
```bash
kube-bench run --benchmark=cis-1.6 --targets node --check=4.2.1
```

**What happened?**
```bash
/root/kube-bench-main/executables-rzdMAHOz82/___224_worker run --benchmark=cis-1.6 --targets node --check=4.2.1 -v=3
....
I0811 17:31:40.822903   34122 check.go:110] -----   Running check 4.2.1   -----
I0811 17:31:40.882694   34122 check.go:299] Command: "/bin/ps -fC kubelet"
I0811 17:31:40.882733   34122 check.go:300] Output:
 "UID        PID  PPID  C STIME TTY          TIME CMD\nroot     48387 48366 19 Aug06 ?        1-02:13:21 kubelet --anonymous-auth=false --network-plugin=cni --registry-burst=10 ....
I0811 17:31:40.886387   34122 check.go:180] failed to run: "/bin/cat /var/lib/kubelet/config.yaml", output: "/bin/cat: /var/lib/kubelet/config.yaml: No such file or directory\n", error: exit status 1
I0811 17:31:40.886411   34122 check.go:186] Command: "/bin/cat /var/lib/kubelet/config.yaml" TestResult: <<EMPTY>> 
I0811 17:31:40.886424   34122 check.go:190] failed to run: "/bin/cat /var/lib/kubelet/config.yaml", output: "/bin/cat: /var/lib/kubelet/config.yaml: No such file or directory\n", error: exit status 1
[INFO] 4 Worker Node Security Configuration
[INFO] 4.2 Kubelet
[FAIL] 4.2.1 Ensure that the anonymous-auth argument is set to false (Automated)
```

**What did you expect to happen:**
[PASS] 4.2.1 Ensure that the anonymous-auth argument is set to false (Automated)

**Environment** 

[What is your version of kube-bench? (run `kube-bench version`)]
build from the latest source code

**Reason**
https://github.com/aquasecurity/kube-bench/blob/main/check/check.go#L195-L212
if it cannot find configuration file, `err` will not be `nil`, so let the false negative result
```go
c.AuditConfigOutput, err = runAudit(c.AuditConfig)
```

Any advice for this issue? Thanks ~

### PR DESCRIPTION
**Pull request by deven0t**
…and config file not found

Suppress the file not found error only when we have audit or auditEnv is defined and they have valid output captured. As, we already have output from audit command. So we can proceed for our tests even though we didnt find config file. 
file not found error: `failed to run: "/test/config.yaml", output: "/bin/sh: line 1: /test/config.yaml: No such file or directory\n", error: exit status 127`

resolve: #1364 
resolve #1242

### CODE REVIEW

**Comment by deven0t** [comment]
@mozillazg @chen-keinan Please review the changes.
Thanks

**Comment by chen-keinan** [comment]
lgtm

**Review by chen-keinan — APPROVED** [review]

File: check/check_test.go [hunk 1]
```diff
@@ -69,6 +69,31 @@ func TestCheck_Run(t *testing.T) {
 			},
 			Expected: PASS,
 		},
+		{
+			name: "Scored checks that pass should PASS when config file is not present",
```
Comment (mozillazg) [inline check/check_test.go:73]: This test case failed. could you please fix this test? Thanks.

**Review by mozillazg — CHANGES_REQUESTED** [review]

File: check/check_test.go (hunk 1 above)
Comment (deven0t) [reply check/check_test.go:73]: Strange, the same testcases is running fine in my local
```
➜  kube-bench git:(deven-bugfix-file-not-found) ✗ make tests
GO111MODULE=on go test -vet all -short -race -timeout 30s -coverprofile=coverage.txt -covermode=atomic ./...
?   	github.com/aquasecurity/kube-bench	[no test files]
ok  	github.com/aquasecurity/kube-bench/check	1.397s	coverage: 91.4% of statements
ok  	github.com/aquasecurity/kube-bench/cmd	11.518s	coverage: 56.5% of statements
?   	github.com/aquasecurity/kube-bench/internal/findings	[no test files]
```

**Review by mozillazg — APPROVED** [review]
LGTM, Thanks for your contribution!

**Review by chen-keinan — APPROVED** [review]

**Comment by chen-keinan** [comment]
@deven0t can you please sign the `cla`

**Comment by deven0t** [comment]
> @deven0t can you please sign the `cla`

Thanks, updated the same. Please rerun the CI pipeline.
The author info used in commit was not a github user that caused this problem.
